version: 2
snapshot:
  widths:
    - 375
    - 470
    - 720
    - 1280
    - 1440
    - 1920
  minHeight: 1024
  percyCSS: ""
discovery:
  allowedHostnames: []
  disallowedHostnames: []
  networkIdleTimeout: 100
upload:
  files: "**/*.{png,jpg,jpeg}"
  ignore: ""
  stripExtensions: false
